### PR TITLE
Generator

### PR DESCRIPTION
**Pull request by BonZirka**

### CODE REVIEW

**Comment by HaskSy** [comment]
Added My Generator, Design, LEETCODE 2022 Added solution for course-schedule, LRUCache realisations, LEETCODE 2022 Added solution for number-of-islands, LEETCODE 2022 Added solution for squares-of-a-sorted-array, LEETCODE 2022 Added solution for flatten-nested-list-iterator), LEETCODE 2022 Added solution for lru-cache, LEETCODE 2022 Added solution for min-stack, LEETCODE 2022 Added solution for implement-stack-using-queues, LEETCODE 2022 Added solution for implement-queue-using-stacks, LEETCODE 2022 Added solution for binary-search-tree-iterator, Added solution for Iterator-3d, Added solution for LinkedList, Triangle solution 21.11.20, LEETCODE 2022 Added solution for reverse-linked-list, LEETCODE 2022 Added solution for middle-of-the-linked-list, LEETCODE 2022 Added solution for palindrome-linked-list, LEETCODE 2022 Added solution for merge-two-sorted-lists, LEETCODE 2022 Added solution for intersection-of-two-linked-lists, LEETCODE 2022 Added solution for sort-list, LEETCODE 2022 Added solution for palindromic-substrings, LEETCODE 2022 Added solution for longest-palindromic-substring, LEETCODE 2022 Added solution for valid-palindrome, LEETCODE 2022 Added solution for group-anagrams, LEETCODE 2022 Added solution for insert-intervals, LEETCODE 2022 Added solution for merge-intervals, LEETCODE 2022 Added solution for non-overlapping-intervals

**Comment by BonZirka** [comment]
Added My Generator, Design, LEETCODE 2022 Added solution for course-schedule, LRUCache realisations, LEETCODE 2022 Added solution for number-of-islands, LEETCODE 2022 Added solution for squares-of-a-sorted-array, LEETCODE 2022 Added solution for flatten-nested-list-iterator), LEETCODE 2022 Added solution for lru-cache, LEETCODE 2022 Added solution for min-stack, LEETCODE 2022 Added solution for implement-stack-using-queues, LEETCODE 2022 Added solution for implement-queue-using-stacks, LEETCODE 2022 Added solution for binary-search-tree-iterator, Added solution for Iterator-3d, Added solution for LinkedList, Triangle solution 21.11.20, LEETCODE 2022 Added solution for reverse-linked-list, LEETCODE 2022 Added solution for middle-of-the-linked-list, LEETCODE 2022 Added solution for palindrome-linked-list, LEETCODE 2022 Added solution for merge-two-sorted-lists, LEETCODE 2022 Added solution for intersection-of-two-linked-lists, LEETCODE 2022 Added solution for sort-list, LEETCODE 2022 Added solution for palindromic-substrings, LEETCODE 2022 Added solution for longest-palindromic-substring, LEETCODE 2022 Added solution for valid-palindrome, LEETCODE 2022 Added solution for group-anagrams, LEETCODE 2022 Added solution for insert-intervals, LEETCODE 2022 Added solution for merge-intervals, LEETCODE 2022 Added solution for non-overlapping-intervals

**Comment by HaskSy** [comment]
Added My Generator, Design, LEETCODE 2022 Added solution for course-schedule, LRUCache realisations, LEETCODE 2022 Added solution for number-of-islands, LEETCODE 2022 Added solution for squares-of-a-sorted-array, LEETCODE 2022 Added solution for flatten-nested-list-iterator), LEETCODE 2022 Added solution for lru-cache, LEETCODE 2022 Added solution for min-stack, LEETCODE 2022 Added solution for implement-stack-using-queues, LEETCODE 2022 Added solution for implement-queue-using-stacks, LEETCODE 2022 Added solution for binary-search-tree-iterator, Added solution for Iterator-3d, Added solution for LinkedList, Triangle solution 21.11.20, LEETCODE 2022 Added solution for reverse-linked-list, LEETCODE 2022 Added solution for middle-of-the-linked-list, LEETCODE 2022 Added solution for palindrome-linked-list, LEETCODE 2022 Added solution for merge-two-sorted-lists, LEETCODE 2022 Added solution for intersection-of-two-linked-lists, LEETCODE 2022 Added solution for sort-list, LEETCODE 2022 Added solution for palindromic-substrings, LEETCODE 2022 Added solution for longest-palindromic-substring, LEETCODE 2022 Added solution for valid-palindrome, LEETCODE 2022 Added solution for group-anagrams, LEETCODE 2022 Added solution for insert-intervals, LEETCODE 2022 Added solution for merge-intervals, LEETCODE 2022 Added solution for non-overlapping-intervals

**Comment by HaskSy** [comment]
Added My Generator, Design, LEETCODE 2022 Added solution for course-schedule, LRUCache realisations, LEETCODE 2022 Added solution for number-of-islands, LEETCODE 2022 Added solution for squares-of-a-sorted-array, LEETCODE 2022 Added solution for flatten-nested-list-iterator), LEETCODE 2022 Added solution for lru-cache, LEETCODE 2022 Added solution for min-stack, LEETCODE 2022 Added solution for implement-stack-using-queues, LEETCODE 2022 Added solution for implement-queue-using-stacks, LEETCODE 2022 Added solution for binary-search-tree-iterator, Added solution for Iterator-3d, Added solution for LinkedList, Triangle solution 21.11.20, LEETCODE 2022 Added solution for reverse-linked-list, LEETCODE 2022 Added solution for middle-of-the-linked-list, LEETCODE 2022 Added solution for palindrome-linked-list, LEETCODE 2022 Added solution for merge-two-sorted-lists, LEETCODE 2022 Added solution for intersection-of-two-linked-lists, LEETCODE 2022 Added solution for sort-list, LEETCODE 2022 Added solution for palindromic-substrings, LEETCODE 2022 Added solution for longest-palindromic-substring, LEETCODE 2022 Added solution for valid-palindrome, LEETCODE 2022 Added solution for group-anagrams, LEETCODE 2022 Added solution for insert-intervals, LEETCODE 2022 Added solution for merge-intervals, LEETCODE 2022 Added solution for non-overlapping-intervals

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files
Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by HaskSy** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by BonZirka** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Comment by BonZirka** [comment]
dagdshsd

**Comment by BonZirka** [comment]
Auto-Verifier finding

Your Commit titles: 
  - Created a generator of .md files

Check result:

    Commit title must start with prefix in ['GENERATOR', 'LEETCODE']
    Commit title must contain group number in ['1021', '1022', '1013', '2021', '2022']
    Commit title action must start with ['Added', 'Deleted', 'Refactored', 'Moved', 'Fixed']

**Pull request merged**
